# Generated by Django 5.2.17 on 2026-09-28 13:46

import datetime

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


def as_aware_utc(value):
    if value is not None and django.utils.timezone.is_naive(value):
        return django.utils.timezone.make_aware(value, datetime.timezone.utc)
    return value


def copy_legacy_users(apps, schema_editor):
    connection = schema_editor.connection
    tables = set(connection.introspection.table_names())
    if "auth_user" not in tables:
        return

    User = apps.get_model("reelo", "User")
    quote_name = connection.ops.quote_name
    with connection.cursor() as cursor:
        cursor.execute(
            f"SELECT id, password, last_login, is_superuser, username, "
            f"first_name, last_name, is_staff, is_active, date_joined, email "
            f"FROM {quote_name('auth_user')}"
        )
        legacy_users = cursor.fetchall()

    User.objects.using(connection.alias).bulk_create(
        [
            User(
                pk=user_id,
                password=password,
                last_login=as_aware_utc(last_login),
                is_superuser=is_superuser,
                username=username,
                first_name=first_name,
                last_name=last_name,
                is_staff=is_staff,
                is_active=is_active,
                date_joined=as_aware_utc(date_joined),
                email=email,
                full_name=" ".join(filter(None, (first_name, last_name))) or username,
            )
            for (
                user_id,
                password,
                last_login,
                is_superuser,
                username,
                first_name,
                last_name,
                is_staff,
                is_active,
                date_joined,
                email,
            ) in legacy_users
        ],
    )

    for table, relation_name, target_name in (
        ("auth_user_groups", "groups", "group_id"),
        ("auth_user_user_permissions", "user_permissions", "permission_id"),
    ):
        if table not in tables:
            continue
        through = User._meta.get_field(relation_name).remote_field.through
        with connection.cursor() as cursor:
            cursor.execute(
                f"SELECT user_id, {quote_name(target_name)} "
                f"FROM {quote_name(table)}"
            )
            relations = cursor.fetchall()
        through.objects.using(connection.alias).bulk_create(
            [
                through(user_id=user_id, **{target_name: target_id})
                for user_id, target_id in relations
            ],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('mobile_no', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RunPython(copy_legacy_users, migrations.RunPython.noop),
    ]
