# Generated by Django 5.2.17 on 2026-10-03 14:23

import django.db.models.deletion
import reelo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelo', '0006_post_likes_post_location_post_saved_by_post_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='attribution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='attribution_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='provider',
            field=models.CharField(default='reelo', max_length=64),
        ),
        migrations.AddField(
            model_name='song',
            name='rights_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Only upload audio Reelo has explicit rights to use.', null=True, upload_to='songs/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='stories/videos/')),
                ('caption', models.CharField(blank=True, max_length=2200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=reelo.models.story_expiry)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='reelo.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('image__isnull', False), ('video__isnull', True)), models.Q(('image__isnull', True), ('video__isnull', False)), _connector='OR'), name='story_has_exactly_one_media')],
            },
        ),
    ]
