# Generated by Django 5.2.17 on 2026-10-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reelo', '0007_song_attribution_song_attribution_url_song_cover_url_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='story',
            name='story_has_exactly_one_media',
        ),
        migrations.AddConstraint(
            model_name='story',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('image__gt', ''), ('video__in', ('', None))), models.Q(('image__in', ('', None)), ('video__gt', '')), _connector='OR'), name='story_has_exactly_one_media'),
        ),
    ]
